### PR TITLE
[#121] Improve sourceMap performance

### PR DESCRIPTION
**Pull request by BrentDouglas**
Writes the files directly to a source map generator removing a bunch of intermediate steps performed when converting between nodes to a generator.

On my laptop this brings the concat step of my build down from ~6m to under 10s.

The current implementation does not seem to add mappings before filler lines (banner, separator and footer) in a consistent manner so this never adds a mapping for the filler text.

### CODE REVIEW

**Comment by danhooper** [comment]
This fix made a big performance improvement for me. +1

**Comment by daedelus-j** [comment]
@BrentDouglas nice work, tried it locally and it sped things up quite a bit. :+1:

**Comment by daedelus-j** [comment]
@XhmikosR any ideas on when this can be merged? really speeds things up

**Comment by kld87** [comment]
+1 I'd also like to see this merged and a new release

**Comment by vladikoff** [comment]
:+1:

**Comment by BrentDouglas** [comment]
Thanks

**Pull request merged**
